import Link from "next/link";

export const metadata = {
  title: "Users Layout",
  description: "Generated by create next app",
};

export default function UsersLayout({ children }) {
  return (
    <>
      <div className="bg-black flex text-white p-4  row justify-between">
        <div className="flex">Logo</div>
        <div className="flex ">
          <ul className="flex">
            <li>
              <Link href={"/users/users-list"}>User List</Link>
            </li>
            <li className="pl-4">Settings</li>
          </ul>
        </div>
      </div>
      <div className=" p-4">{children}</div>
    </>
  );
}
